// Code generated by MockGen. DO NOT EDIT.
// Source: resources/s3files-api-interface.go
//
// Generated by this command:
//
//	mockgen -source=resources/s3files-api-interface.go -destination=mocks/mock_s3filesv2/mock.go
//

// Package mock_s3filesv2 is a generated GoMock package.
package mock_s3filesv2

import (
	context "context"
	reflect "reflect"

	s3files "github.com/aws/aws-sdk-go-v2/service/s3files"
	gomock "go.uber.org/mock/gomock"
)

// MockS3FilesAPI is a mock of S3FilesAPI interface.
type MockS3FilesAPI struct {
	ctrl     *gomock.Controller
	recorder *MockS3FilesAPIMockRecorder
	isgomock struct{}
}

// MockS3FilesAPIMockRecorder is the mock recorder for MockS3FilesAPI.
type MockS3FilesAPIMockRecorder struct {
	mock *MockS3FilesAPI
}

// NewMockS3FilesAPI creates a new mock instance.
func NewMockS3FilesAPI(ctrl *gomock.Controller) *MockS3FilesAPI {
	mock := &MockS3FilesAPI{ctrl: ctrl}
	mock.recorder = &MockS3FilesAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3FilesAPI) EXPECT() *MockS3FilesAPIMockRecorder {
	return m.recorder
}

// DeleteAccessPoint mocks base method.
func (m *MockS3FilesAPI) DeleteAccessPoint(ctx context.Context, params *s3files.DeleteAccessPointInput, optFns ...func(*s3files.Options)) (*s3files.DeleteAccessPointOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteAccessPoint", varargs...)
	ret0, _ := ret[0].(*s3files.DeleteAccessPointOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAccessPoint indicates an expected call of DeleteAccessPoint.
func (mr *MockS3FilesAPIMockRecorder) DeleteAccessPoint(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessPoint", reflect.TypeOf((*MockS3FilesAPI)(nil).DeleteAccessPoint), varargs...)
}

// DeleteFileSystem mocks base method.
func (m *MockS3FilesAPI) DeleteFileSystem(ctx context.Context, params *s3files.DeleteFileSystemInput, optFns ...func(*s3files.Options)) (*s3files.DeleteFileSystemOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteFileSystem", varargs...)
	ret0, _ := ret[0].(*s3files.DeleteFileSystemOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFileSystem indicates an expected call of DeleteFileSystem.
func (mr *MockS3FilesAPIMockRecorder) DeleteFileSystem(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFileSystem", reflect.TypeOf((*MockS3FilesAPI)(nil).DeleteFileSystem), varargs...)
}

// DeleteMountTarget mocks base method.
func (m *MockS3FilesAPI) DeleteMountTarget(ctx context.Context, params *s3files.DeleteMountTargetInput, optFns ...func(*s3files.Options)) (*s3files.DeleteMountTargetOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteMountTarget", varargs...)
	ret0, _ := ret[0].(*s3files.DeleteMountTargetOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMountTarget indicates an expected call of DeleteMountTarget.
func (mr *MockS3FilesAPIMockRecorder) DeleteMountTarget(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMountTarget", reflect.TypeOf((*MockS3FilesAPI)(nil).DeleteMountTarget), varargs...)
}

// ListAccessPoints mocks base method.
func (m *MockS3FilesAPI) ListAccessPoints(ctx context.Context, params *s3files.ListAccessPointsInput, optFns ...func(*s3files.Options)) (*s3files.ListAccessPointsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListAccessPoints", varargs...)
	ret0, _ := ret[0].(*s3files.ListAccessPointsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccessPoints indicates an expected call of ListAccessPoints.
func (mr *MockS3FilesAPIMockRecorder) ListAccessPoints(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccessPoints", reflect.TypeOf((*MockS3FilesAPI)(nil).ListAccessPoints), varargs...)
}

// ListFileSystems mocks base method.
func (m *MockS3FilesAPI) ListFileSystems(ctx context.Context, params *s3files.ListFileSystemsInput, optFns ...func(*s3files.Options)) (*s3files.ListFileSystemsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListFileSystems", varargs...)
	ret0, _ := ret[0].(*s3files.ListFileSystemsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFileSystems indicates an expected call of ListFileSystems.
func (mr *MockS3FilesAPIMockRecorder) ListFileSystems(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFileSystems", reflect.TypeOf((*MockS3FilesAPI)(nil).ListFileSystems), varargs...)
}

// ListMountTargets mocks base method.
func (m *MockS3FilesAPI) ListMountTargets(ctx context.Context, params *s3files.ListMountTargetsInput, optFns ...func(*s3files.Options)) (*s3files.ListMountTargetsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListMountTargets", varargs...)
	ret0, _ := ret[0].(*s3files.ListMountTargetsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMountTargets indicates an expected call of ListMountTargets.
func (mr *MockS3FilesAPIMockRecorder) ListMountTargets(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMountTargets", reflect.TypeOf((*MockS3FilesAPI)(nil).ListMountTargets), varargs...)
}
