// Code generated by MockGen. DO NOT EDIT.
// Source: resources/ec2-host-api-interface.go
//
// Generated by this command:
//
//	mockgen -source=resources/ec2-host-api-interface.go -destination=mocks/mock_ec2host/mock.go -package=mock_ec2host
//

// Package mock_ec2host is a generated GoMock package.
package mock_ec2host

import (
	context "context"
	reflect "reflect"

	ec2 "github.com/aws/aws-sdk-go-v2/service/ec2"
	gomock "go.uber.org/mock/gomock"
)

// MockEC2HostAPI is a mock of EC2HostAPI interface.
type MockEC2HostAPI struct {
	ctrl     *gomock.Controller
	recorder *MockEC2HostAPIMockRecorder
	isgomock struct{}
}

// MockEC2HostAPIMockRecorder is the mock recorder for MockEC2HostAPI.
type MockEC2HostAPIMockRecorder struct {
	mock *MockEC2HostAPI
}

// NewMockEC2HostAPI creates a new mock instance.
func NewMockEC2HostAPI(ctrl *gomock.Controller) *MockEC2HostAPI {
	mock := &MockEC2HostAPI{ctrl: ctrl}
	mock.recorder = &MockEC2HostAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEC2HostAPI) EXPECT() *MockEC2HostAPIMockRecorder {
	return m.recorder
}

// ReleaseHosts mocks base method.
func (m *MockEC2HostAPI) ReleaseHosts(ctx context.Context, params *ec2.ReleaseHostsInput, optFns ...func(*ec2.Options)) (*ec2.ReleaseHostsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReleaseHosts", varargs...)
	ret0, _ := ret[0].(*ec2.ReleaseHostsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseHosts indicates an expected call of ReleaseHosts.
func (mr *MockEC2HostAPIMockRecorder) ReleaseHosts(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseHosts", reflect.TypeOf((*MockEC2HostAPI)(nil).ReleaseHosts), varargs...)
}
