version: 2
dist: releases
release:
  github:
    owner: ekristen
    name: aws-nuke
builds:
  - id: default
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -extldflags="-static"
      - -X '{{ .ModulePath }}/pkg/common.SUMMARY=v{{ .Version }}'
      - -X '{{ .ModulePath }}/pkg/common.BRANCH={{ .Branch }}'
      - -X '{{ .ModulePath }}/pkg/common.VERSION={{ .Tag }}'
      - -X '{{ .ModulePath }}/pkg/common.COMMIT={{ .Commit }}'
    hooks:
      post:
        - cmd: |
            {{- if eq .Os "darwin" -}}
            quill sign-and-notarize "{{ .Path }}" --dry-run={{ .IsSnapshot }} --ad-hoc={{ .IsSnapshot }} -vv
            {{- else -}}
            true
            {{- end -}}
          env:
            - QUILL_LOG_FILE=/tmp/quill-{{ .Target }}.log
archives:
  - id: default
    ids:
      - default
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ .Arm }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
dockers_v2:
  - dockerfile: Dockerfile
    images:
      - ghcr.io/ekristen/aws-nuke
    tags:
      - v{{ .Version }}
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "https://github.com/ekristen/aws-nuke"
    flags:
      - "--target=goreleaser"
      - "--pull"
signs:
  - ids:
      - default
    cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args:
      [
        "sign-blob",
        "--yes",
        "--oidc-provider=github",
        "--oidc-issuer=https://token.actions.githubusercontent.com",
        "--output-certificate=${certificate}",
        "--output-signature=${signature}",
        "${artifact}",
      ]
    artifacts: all
docker_signs:
  - ids:
      - default
    artifacts: all
    cmd: cosign
    args:
      [
        "sign",
        "--yes",
        "--oidc-provider=github",
        "--oidc-issuer=https://token.actions.githubusercontent.com",
        "--output-certificate=${certificate}",
        "--output-signature=${signature}",
        "${artifact}",
      ]
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: '{{ trimprefix .Summary "v" }}'
changelog:
  disable: true
