site_name: AWS Nuke
site_url: https://ekristen.github.io/aws-nuke
site_author: Erik Kristensen
site_description: >-
  AWS Nuke is a tool to clean up your AWS account by nuking (deleting) all resources within it.

repo_name: ekristen/aws-nuke
repo_url: https://github.com/ekristen/aws-nuke

copyright: Copyright &copy; 2024 - Erik Kristensen

site_dir: public

# Configuration
theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - toc.follow
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

# Page tree
nav:
  - Getting Started:
    - Introduction: index.md
    - Warning: warning.md
    - Install: installation.md
    - Authentication: auth.md
    - Quick Start: quick-start.md
  - Config:
    - Overview: config.md
    - Filtering: config-filtering.md
    - Presets: config-presets.md
    - Custom Endpoints: config-custom-endpoints.md
    - Migration Guide: config-migration.md
  - Development:
    - Overview: development.md
    - Resources: resources.md
    - Releases: releases.md
    - Testing: testing.md

