// Code generated by MockGen. DO NOT EDIT.
// Source: resources/securityhub-api-interface.go
//
// Generated by this command:
//
//	mockgen -source=resources/securityhub-api-interface.go -destination=mocks/mock_securityhub/mock.go -package=mock_securityhub
//

// Package mock_securityhub is a generated GoMock package.
package mock_securityhub

import (
	context "context"
	reflect "reflect"

	securityhub "github.com/aws/aws-sdk-go-v2/service/securityhub"
	gomock "go.uber.org/mock/gomock"
)

// MockSecurityHubV2API is a mock of SecurityHubV2API interface.
type MockSecurityHubV2API struct {
	ctrl     *gomock.Controller
	recorder *MockSecurityHubV2APIMockRecorder
	isgomock struct{}
}

// MockSecurityHubV2APIMockRecorder is the mock recorder for MockSecurityHubV2API.
type MockSecurityHubV2APIMockRecorder struct {
	mock *MockSecurityHubV2API
}

// NewMockSecurityHubV2API creates a new mock instance.
func NewMockSecurityHubV2API(ctrl *gomock.Controller) *MockSecurityHubV2API {
	mock := &MockSecurityHubV2API{ctrl: ctrl}
	mock.recorder = &MockSecurityHubV2APIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecurityHubV2API) EXPECT() *MockSecurityHubV2APIMockRecorder {
	return m.recorder
}

// DescribeSecurityHubV2 mocks base method.
func (m *MockSecurityHubV2API) DescribeSecurityHubV2(ctx context.Context, params *securityhub.DescribeSecurityHubV2Input, optFns ...func(*securityhub.Options)) (*securityhub.DescribeSecurityHubV2Output, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeSecurityHubV2", varargs...)
	ret0, _ := ret[0].(*securityhub.DescribeSecurityHubV2Output)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeSecurityHubV2 indicates an expected call of DescribeSecurityHubV2.
func (mr *MockSecurityHubV2APIMockRecorder) DescribeSecurityHubV2(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeSecurityHubV2", reflect.TypeOf((*MockSecurityHubV2API)(nil).DescribeSecurityHubV2), varargs...)
}

// DisableSecurityHubV2 mocks base method.
func (m *MockSecurityHubV2API) DisableSecurityHubV2(ctx context.Context, params *securityhub.DisableSecurityHubV2Input, optFns ...func(*securityhub.Options)) (*securityhub.DisableSecurityHubV2Output, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DisableSecurityHubV2", varargs...)
	ret0, _ := ret[0].(*securityhub.DisableSecurityHubV2Output)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DisableSecurityHubV2 indicates an expected call of DisableSecurityHubV2.
func (mr *MockSecurityHubV2APIMockRecorder) DisableSecurityHubV2(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableSecurityHubV2", reflect.TypeOf((*MockSecurityHubV2API)(nil).DisableSecurityHubV2), varargs...)
}
