// Code generated by MockGen. DO NOT EDIT.
// Source: resources/rds-api-interface.go
//
// Generated by this command:
//
//	mockgen -source=resources/rds-api-interface.go -destination=mocks/mock_rdsv2/mock.go -package mock_rdsv2
//

// Package mock_rdsv2 is a generated GoMock package.
package mock_rdsv2

import (
	context "context"
	reflect "reflect"

	rds "github.com/aws/aws-sdk-go-v2/service/rds"
	gomock "go.uber.org/mock/gomock"
)

// MockRDSAPI is a mock of RDSAPI interface.
type MockRDSAPI struct {
	ctrl     *gomock.Controller
	recorder *MockRDSAPIMockRecorder
	isgomock struct{}
}

// MockRDSAPIMockRecorder is the mock recorder for MockRDSAPI.
type MockRDSAPIMockRecorder struct {
	mock *MockRDSAPI
}

// NewMockRDSAPI creates a new mock instance.
func NewMockRDSAPI(ctrl *gomock.Controller) *MockRDSAPI {
	mock := &MockRDSAPI{ctrl: ctrl}
	mock.recorder = &MockRDSAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRDSAPI) EXPECT() *MockRDSAPIMockRecorder {
	return m.recorder
}

// DeleteGlobalCluster mocks base method.
func (m *MockRDSAPI) DeleteGlobalCluster(ctx context.Context, params *rds.DeleteGlobalClusterInput, optFns ...func(*rds.Options)) (*rds.DeleteGlobalClusterOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteGlobalCluster", varargs...)
	ret0, _ := ret[0].(*rds.DeleteGlobalClusterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteGlobalCluster indicates an expected call of DeleteGlobalCluster.
func (mr *MockRDSAPIMockRecorder) DeleteGlobalCluster(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGlobalCluster", reflect.TypeOf((*MockRDSAPI)(nil).DeleteGlobalCluster), varargs...)
}

// DescribeGlobalClusters mocks base method.
func (m *MockRDSAPI) DescribeGlobalClusters(ctx context.Context, params *rds.DescribeGlobalClustersInput, optFns ...func(*rds.Options)) (*rds.DescribeGlobalClustersOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeGlobalClusters", varargs...)
	ret0, _ := ret[0].(*rds.DescribeGlobalClustersOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeGlobalClusters indicates an expected call of DescribeGlobalClusters.
func (mr *MockRDSAPIMockRecorder) DescribeGlobalClusters(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeGlobalClusters", reflect.TypeOf((*MockRDSAPI)(nil).DescribeGlobalClusters), varargs...)
}

// ListTagsForResource mocks base method.
func (m *MockRDSAPI) ListTagsForResource(ctx context.Context, params *rds.ListTagsForResourceInput, optFns ...func(*rds.Options)) (*rds.ListTagsForResourceOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTagsForResource", varargs...)
	ret0, _ := ret[0].(*rds.ListTagsForResourceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTagsForResource indicates an expected call of ListTagsForResource.
func (mr *MockRDSAPIMockRecorder) ListTagsForResource(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTagsForResource", reflect.TypeOf((*MockRDSAPI)(nil).ListTagsForResource), varargs...)
}

// ModifyGlobalCluster mocks base method.
func (m *MockRDSAPI) ModifyGlobalCluster(ctx context.Context, params *rds.ModifyGlobalClusterInput, optFns ...func(*rds.Options)) (*rds.ModifyGlobalClusterOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ModifyGlobalCluster", varargs...)
	ret0, _ := ret[0].(*rds.ModifyGlobalClusterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModifyGlobalCluster indicates an expected call of ModifyGlobalCluster.
func (mr *MockRDSAPIMockRecorder) ModifyGlobalCluster(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyGlobalCluster", reflect.TypeOf((*MockRDSAPI)(nil).ModifyGlobalCluster), varargs...)
}

// RemoveFromGlobalCluster mocks base method.
func (m *MockRDSAPI) RemoveFromGlobalCluster(ctx context.Context, params *rds.RemoveFromGlobalClusterInput, optFns ...func(*rds.Options)) (*rds.RemoveFromGlobalClusterOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveFromGlobalCluster", varargs...)
	ret0, _ := ret[0].(*rds.RemoveFromGlobalClusterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveFromGlobalCluster indicates an expected call of RemoveFromGlobalCluster.
func (mr *MockRDSAPIMockRecorder) RemoveFromGlobalCluster(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromGlobalCluster", reflect.TypeOf((*MockRDSAPI)(nil).RemoveFromGlobalCluster), varargs...)
}
