// Code generated by MockGen. DO NOT EDIT.
// Source: resources/timestreaminfluxdb-api-interface.go
//
// Generated by this command:
//
//	mockgen -source resources/timestreaminfluxdb-api-interface.go
//

package mock_timestreaminfluxdb

import (
	context "context"
	reflect "reflect"

	timestreaminfluxdb "github.com/aws/aws-sdk-go-v2/service/timestreaminfluxdb"
	gomock "go.uber.org/mock/gomock"
)

// MockTimestreamInfluxDBAPI is a mock of TimestreamInfluxDBAPI interface.
type MockTimestreamInfluxDBAPI struct {
	ctrl     *gomock.Controller
	recorder *MockTimestreamInfluxDBAPIMockRecorder
	isgomock struct{}
}

// MockTimestreamInfluxDBAPIMockRecorder is the mock recorder for MockTimestreamInfluxDBAPI.
type MockTimestreamInfluxDBAPIMockRecorder struct {
	mock *MockTimestreamInfluxDBAPI
}

// NewMockTimestreamInfluxDBAPI creates a new mock instance.
func NewMockTimestreamInfluxDBAPI(ctrl *gomock.Controller) *MockTimestreamInfluxDBAPI {
	mock := &MockTimestreamInfluxDBAPI{ctrl: ctrl}
	mock.recorder = &MockTimestreamInfluxDBAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimestreamInfluxDBAPI) EXPECT() *MockTimestreamInfluxDBAPIMockRecorder {
	return m.recorder
}

// DeleteDbInstance mocks base method.
func (m *MockTimestreamInfluxDBAPI) DeleteDbInstance(ctx context.Context, params *timestreaminfluxdb.DeleteDbInstanceInput, optFns ...func(*timestreaminfluxdb.Options)) (*timestreaminfluxdb.DeleteDbInstanceOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteDbInstance", varargs...)
	ret0, _ := ret[0].(*timestreaminfluxdb.DeleteDbInstanceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDbInstance indicates an expected call of DeleteDbInstance.
func (mr *MockTimestreamInfluxDBAPIMockRecorder) DeleteDbInstance(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDbInstance", reflect.TypeOf((*MockTimestreamInfluxDBAPI)(nil).DeleteDbInstance), varargs...)
}

// ListDbInstances mocks base method.
func (m *MockTimestreamInfluxDBAPI) ListDbInstances(ctx context.Context, params *timestreaminfluxdb.ListDbInstancesInput, optFns ...func(*timestreaminfluxdb.Options)) (*timestreaminfluxdb.ListDbInstancesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListDbInstances", varargs...)
	ret0, _ := ret[0].(*timestreaminfluxdb.ListDbInstancesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDbInstances indicates an expected call of ListDbInstances.
func (mr *MockTimestreamInfluxDBAPIMockRecorder) ListDbInstances(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDbInstances", reflect.TypeOf((*MockTimestreamInfluxDBAPI)(nil).ListDbInstances), varargs...)
}

// ListTagsForResource mocks base method.
func (m *MockTimestreamInfluxDBAPI) ListTagsForResource(ctx context.Context, params *timestreaminfluxdb.ListTagsForResourceInput, optFns ...func(*timestreaminfluxdb.Options)) (*timestreaminfluxdb.ListTagsForResourceOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTagsForResource", varargs...)
	ret0, _ := ret[0].(*timestreaminfluxdb.ListTagsForResourceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTagsForResource indicates an expected call of ListTagsForResource.
func (mr *MockTimestreamInfluxDBAPIMockRecorder) ListTagsForResource(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTagsForResource", reflect.TypeOf((*MockTimestreamInfluxDBAPI)(nil).ListTagsForResource), varargs...)
}
