// Code generated by MockGen. DO NOT EDIT.
// Source: resources/translate-api-interface.go
//
// Generated by this command:
//
//	mockgen -source resources/translate-api-interface.go
//

package mock_translate

import (
	context "context"
	reflect "reflect"

	translate "github.com/aws/aws-sdk-go-v2/service/translate"
	gomock "go.uber.org/mock/gomock"
)

// MockTranslateAPI is a mock of TranslateAPI interface.
type MockTranslateAPI struct {
	ctrl     *gomock.Controller
	recorder *MockTranslateAPIMockRecorder
	isgomock struct{}
}

// MockTranslateAPIMockRecorder is the mock recorder for MockTranslateAPI.
type MockTranslateAPIMockRecorder struct {
	mock *MockTranslateAPI
}

// NewMockTranslateAPI creates a new mock instance.
func NewMockTranslateAPI(ctrl *gomock.Controller) *MockTranslateAPI {
	mock := &MockTranslateAPI{ctrl: ctrl}
	mock.recorder = &MockTranslateAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslateAPI) EXPECT() *MockTranslateAPIMockRecorder {
	return m.recorder
}

// DeleteParallelData mocks base method.
func (m *MockTranslateAPI) DeleteParallelData(ctx context.Context, params *translate.DeleteParallelDataInput, optFns ...func(*translate.Options)) (*translate.DeleteParallelDataOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteParallelData", varargs...)
	ret0, _ := ret[0].(*translate.DeleteParallelDataOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteParallelData indicates an expected call of DeleteParallelData.
func (mr *MockTranslateAPIMockRecorder) DeleteParallelData(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteParallelData", reflect.TypeOf((*MockTranslateAPI)(nil).DeleteParallelData), varargs...)
}

// DeleteTerminology mocks base method.
func (m *MockTranslateAPI) DeleteTerminology(ctx context.Context, params *translate.DeleteTerminologyInput, optFns ...func(*translate.Options)) (*translate.DeleteTerminologyOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteTerminology", varargs...)
	ret0, _ := ret[0].(*translate.DeleteTerminologyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTerminology indicates an expected call of DeleteTerminology.
func (mr *MockTranslateAPIMockRecorder) DeleteTerminology(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTerminology", reflect.TypeOf((*MockTranslateAPI)(nil).DeleteTerminology), varargs...)
}

// ListParallelData mocks base method.
func (m *MockTranslateAPI) ListParallelData(ctx context.Context, params *translate.ListParallelDataInput, optFns ...func(*translate.Options)) (*translate.ListParallelDataOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListParallelData", varargs...)
	ret0, _ := ret[0].(*translate.ListParallelDataOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListParallelData indicates an expected call of ListParallelData.
func (mr *MockTranslateAPIMockRecorder) ListParallelData(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListParallelData", reflect.TypeOf((*MockTranslateAPI)(nil).ListParallelData), varargs...)
}

// ListTerminologies mocks base method.
func (m *MockTranslateAPI) ListTerminologies(ctx context.Context, params *translate.ListTerminologiesInput, optFns ...func(*translate.Options)) (*translate.ListTerminologiesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTerminologies", varargs...)
	ret0, _ := ret[0].(*translate.ListTerminologiesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTerminologies indicates an expected call of ListTerminologies.
func (mr *MockTranslateAPIMockRecorder) ListTerminologies(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTerminologies", reflect.TypeOf((*MockTranslateAPI)(nil).ListTerminologies), varargs...)
}

// ListTextTranslationJobs mocks base method.
func (m *MockTranslateAPI) ListTextTranslationJobs(ctx context.Context, params *translate.ListTextTranslationJobsInput, optFns ...func(*translate.Options)) (*translate.ListTextTranslationJobsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTextTranslationJobs", varargs...)
	ret0, _ := ret[0].(*translate.ListTextTranslationJobsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTextTranslationJobs indicates an expected call of ListTextTranslationJobs.
func (mr *MockTranslateAPIMockRecorder) ListTextTranslationJobs(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTextTranslationJobs", reflect.TypeOf((*MockTranslateAPI)(nil).ListTextTranslationJobs), varargs...)
}

// StopTextTranslationJob mocks base method.
func (m *MockTranslateAPI) StopTextTranslationJob(ctx context.Context, params *translate.StopTextTranslationJobInput, optFns ...func(*translate.Options)) (*translate.StopTextTranslationJobOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StopTextTranslationJob", varargs...)
	ret0, _ := ret[0].(*translate.StopTextTranslationJobOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StopTextTranslationJob indicates an expected call of StopTextTranslationJob.
func (mr *MockTranslateAPIMockRecorder) StopTextTranslationJob(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopTextTranslationJob", reflect.TypeOf((*MockTranslateAPI)(nil).StopTextTranslationJob), varargs...)
}
