// Code generated by MockGen. DO NOT EDIT.
// Source: resources/ram-api-interface.go
//
// Generated by this command:
//
//	mockgen -source resources/ram-api-interface.go
//

package mock_ram

import (
	context "context"
	reflect "reflect"

	ram "github.com/aws/aws-sdk-go-v2/service/ram"
	gomock "go.uber.org/mock/gomock"
)

// MockRAMAPI is a mock of RAMAPI interface.
type MockRAMAPI struct {
	ctrl     *gomock.Controller
	recorder *MockRAMAPIMockRecorder
	isgomock struct{}
}

// MockRAMAPIMockRecorder is the mock recorder for MockRAMAPI.
type MockRAMAPIMockRecorder struct {
	mock *MockRAMAPI
}

// NewMockRAMAPI creates a new mock instance.
func NewMockRAMAPI(ctrl *gomock.Controller) *MockRAMAPI {
	mock := &MockRAMAPI{ctrl: ctrl}
	mock.recorder = &MockRAMAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRAMAPI) EXPECT() *MockRAMAPIMockRecorder {
	return m.recorder
}

// DeleteResourceShare mocks base method.
func (m *MockRAMAPI) DeleteResourceShare(ctx context.Context, params *ram.DeleteResourceShareInput, optFns ...func(*ram.Options)) (*ram.DeleteResourceShareOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteResourceShare", varargs...)
	ret0, _ := ret[0].(*ram.DeleteResourceShareOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteResourceShare indicates an expected call of DeleteResourceShare.
func (mr *MockRAMAPIMockRecorder) DeleteResourceShare(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteResourceShare", reflect.TypeOf((*MockRAMAPI)(nil).DeleteResourceShare), varargs...)
}

// GetResourceShares mocks base method.
func (m *MockRAMAPI) GetResourceShares(ctx context.Context, params *ram.GetResourceSharesInput, optFns ...func(*ram.Options)) (*ram.GetResourceSharesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetResourceShares", varargs...)
	ret0, _ := ret[0].(*ram.GetResourceSharesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResourceShares indicates an expected call of GetResourceShares.
func (mr *MockRAMAPIMockRecorder) GetResourceShares(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourceShares", reflect.TypeOf((*MockRAMAPI)(nil).GetResourceShares), varargs...)
}
