// Code generated by MockGen. DO NOT EDIT.
// Source: resources/route53-resolver-firewall-rule-group.go
//
// Generated by this command:
//
//	mockgen -source=resources/route53-resolver-firewall-rule-group.go Route53ResolverAPI
//

// Package mock_resources is a generated GoMock package.
package mock_route53resolverv2

import (
	context "context"
	reflect "reflect"

	route53resolver "github.com/aws/aws-sdk-go-v2/service/route53resolver"
	gomock "go.uber.org/mock/gomock"
)


// MockRoute53ResolverAPI is a mock of Route53ResolverAPI interface.
type MockRoute53ResolverAPI struct {
	ctrl     *gomock.Controller
	recorder *MockRoute53ResolverAPIMockRecorder
	isgomock struct{}
}

// MockRoute53ResolverAPIMockRecorder is the mock recorder for MockRoute53ResolverAPI.
type MockRoute53ResolverAPIMockRecorder struct {
	mock *MockRoute53ResolverAPI
}

// NewMockRoute53ResolverAPI creates a new mock instance.
func NewMockRoute53ResolverAPI(ctrl *gomock.Controller) *MockRoute53ResolverAPI {
	mock := &MockRoute53ResolverAPI{ctrl: ctrl}
	mock.recorder = &MockRoute53ResolverAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoute53ResolverAPI) EXPECT() *MockRoute53ResolverAPIMockRecorder {
	return m.recorder
}

// DeleteFirewallDomainList mocks base method.
func (m *MockRoute53ResolverAPI) DeleteFirewallDomainList(ctx context.Context, params *route53resolver.DeleteFirewallDomainListInput, optFns ...func(*route53resolver.Options)) (*route53resolver.DeleteFirewallDomainListOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteFirewallDomainList", varargs...)
	ret0, _ := ret[0].(*route53resolver.DeleteFirewallDomainListOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFirewallDomainList indicates an expected call of DeleteFirewallDomainList.
func (mr *MockRoute53ResolverAPIMockRecorder) DeleteFirewallDomainList(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFirewallDomainList", reflect.TypeOf((*MockRoute53ResolverAPI)(nil).DeleteFirewallDomainList), varargs...)
}

// DeleteFirewallRule mocks base method.
func (m *MockRoute53ResolverAPI) DeleteFirewallRule(ctx context.Context, params *route53resolver.DeleteFirewallRuleInput, optFns ...func(*route53resolver.Options)) (*route53resolver.DeleteFirewallRuleOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteFirewallRule", varargs...)
	ret0, _ := ret[0].(*route53resolver.DeleteFirewallRuleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFirewallRule indicates an expected call of DeleteFirewallRule.
func (mr *MockRoute53ResolverAPIMockRecorder) DeleteFirewallRule(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFirewallRule", reflect.TypeOf((*MockRoute53ResolverAPI)(nil).DeleteFirewallRule), varargs...)
}

// DeleteFirewallRuleGroup mocks base method.
func (m *MockRoute53ResolverAPI) DeleteFirewallRuleGroup(ctx context.Context, params *route53resolver.DeleteFirewallRuleGroupInput, optFns ...func(*route53resolver.Options)) (*route53resolver.DeleteFirewallRuleGroupOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteFirewallRuleGroup", varargs...)
	ret0, _ := ret[0].(*route53resolver.DeleteFirewallRuleGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFirewallRuleGroup indicates an expected call of DeleteFirewallRuleGroup.
func (mr *MockRoute53ResolverAPIMockRecorder) DeleteFirewallRuleGroup(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFirewallRuleGroup", reflect.TypeOf((*MockRoute53ResolverAPI)(nil).DeleteFirewallRuleGroup), varargs...)
}

// DeleteResolverQueryLogConfig mocks base method.
func (m *MockRoute53ResolverAPI) DeleteResolverQueryLogConfig(ctx context.Context, params *route53resolver.DeleteResolverQueryLogConfigInput, optFns ...func(*route53resolver.Options)) (*route53resolver.DeleteResolverQueryLogConfigOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteResolverQueryLogConfig", varargs...)
	ret0, _ := ret[0].(*route53resolver.DeleteResolverQueryLogConfigOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteResolverQueryLogConfig indicates an expected call of DeleteResolverQueryLogConfig.
func (mr *MockRoute53ResolverAPIMockRecorder) DeleteResolverQueryLogConfig(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteResolverQueryLogConfig", reflect.TypeOf((*MockRoute53ResolverAPI)(nil).DeleteResolverQueryLogConfig), varargs...)
}

// DisassociateFirewallRuleGroup mocks base method.
func (m *MockRoute53ResolverAPI) DisassociateFirewallRuleGroup(ctx context.Context, params *route53resolver.DisassociateFirewallRuleGroupInput, optFns ...func(*route53resolver.Options)) (*route53resolver.DisassociateFirewallRuleGroupOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DisassociateFirewallRuleGroup", varargs...)
	ret0, _ := ret[0].(*route53resolver.DisassociateFirewallRuleGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DisassociateFirewallRuleGroup indicates an expected call of DisassociateFirewallRuleGroup.
func (mr *MockRoute53ResolverAPIMockRecorder) DisassociateFirewallRuleGroup(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisassociateFirewallRuleGroup", reflect.TypeOf((*MockRoute53ResolverAPI)(nil).DisassociateFirewallRuleGroup), varargs...)
}

// DisassociateResolverQueryLogConfig mocks base method.
func (m *MockRoute53ResolverAPI) DisassociateResolverQueryLogConfig(ctx context.Context, params *route53resolver.DisassociateResolverQueryLogConfigInput, optFns ...func(*route53resolver.Options)) (*route53resolver.DisassociateResolverQueryLogConfigOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DisassociateResolverQueryLogConfig", varargs...)
	ret0, _ := ret[0].(*route53resolver.DisassociateResolverQueryLogConfigOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DisassociateResolverQueryLogConfig indicates an expected call of DisassociateResolverQueryLogConfig.
func (mr *MockRoute53ResolverAPIMockRecorder) DisassociateResolverQueryLogConfig(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisassociateResolverQueryLogConfig", reflect.TypeOf((*MockRoute53ResolverAPI)(nil).DisassociateResolverQueryLogConfig), varargs...)
}

// ListFirewallDomainLists mocks base method.
func (m *MockRoute53ResolverAPI) ListFirewallDomainLists(ctx context.Context, params *route53resolver.ListFirewallDomainListsInput, optFns ...func(*route53resolver.Options)) (*route53resolver.ListFirewallDomainListsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListFirewallDomainLists", varargs...)
	ret0, _ := ret[0].(*route53resolver.ListFirewallDomainListsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFirewallDomainLists indicates an expected call of ListFirewallDomainLists.
func (mr *MockRoute53ResolverAPIMockRecorder) ListFirewallDomainLists(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFirewallDomainLists", reflect.TypeOf((*MockRoute53ResolverAPI)(nil).ListFirewallDomainLists), varargs...)
}

// ListFirewallRuleGroupAssociations mocks base method.
func (m *MockRoute53ResolverAPI) ListFirewallRuleGroupAssociations(ctx context.Context, params *route53resolver.ListFirewallRuleGroupAssociationsInput, optFns ...func(*route53resolver.Options)) (*route53resolver.ListFirewallRuleGroupAssociationsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListFirewallRuleGroupAssociations", varargs...)
	ret0, _ := ret[0].(*route53resolver.ListFirewallRuleGroupAssociationsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFirewallRuleGroupAssociations indicates an expected call of ListFirewallRuleGroupAssociations.
func (mr *MockRoute53ResolverAPIMockRecorder) ListFirewallRuleGroupAssociations(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFirewallRuleGroupAssociations", reflect.TypeOf((*MockRoute53ResolverAPI)(nil).ListFirewallRuleGroupAssociations), varargs...)
}

// ListFirewallRuleGroups mocks base method.
func (m *MockRoute53ResolverAPI) ListFirewallRuleGroups(ctx context.Context, params *route53resolver.ListFirewallRuleGroupsInput, optFns ...func(*route53resolver.Options)) (*route53resolver.ListFirewallRuleGroupsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListFirewallRuleGroups", varargs...)
	ret0, _ := ret[0].(*route53resolver.ListFirewallRuleGroupsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFirewallRuleGroups indicates an expected call of ListFirewallRuleGroups.
func (mr *MockRoute53ResolverAPIMockRecorder) ListFirewallRuleGroups(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFirewallRuleGroups", reflect.TypeOf((*MockRoute53ResolverAPI)(nil).ListFirewallRuleGroups), varargs...)
}

// ListFirewallRules mocks base method.
func (m *MockRoute53ResolverAPI) ListFirewallRules(ctx context.Context, params *route53resolver.ListFirewallRulesInput, optFns ...func(*route53resolver.Options)) (*route53resolver.ListFirewallRulesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListFirewallRules", varargs...)
	ret0, _ := ret[0].(*route53resolver.ListFirewallRulesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFirewallRules indicates an expected call of ListFirewallRules.
func (mr *MockRoute53ResolverAPIMockRecorder) ListFirewallRules(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFirewallRules", reflect.TypeOf((*MockRoute53ResolverAPI)(nil).ListFirewallRules), varargs...)
}

// ListResolverQueryLogConfigAssociations mocks base method.
func (m *MockRoute53ResolverAPI) ListResolverQueryLogConfigAssociations(ctx context.Context, params *route53resolver.ListResolverQueryLogConfigAssociationsInput, optFns ...func(*route53resolver.Options)) (*route53resolver.ListResolverQueryLogConfigAssociationsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListResolverQueryLogConfigAssociations", varargs...)
	ret0, _ := ret[0].(*route53resolver.ListResolverQueryLogConfigAssociationsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListResolverQueryLogConfigAssociations indicates an expected call of ListResolverQueryLogConfigAssociations.
func (mr *MockRoute53ResolverAPIMockRecorder) ListResolverQueryLogConfigAssociations(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResolverQueryLogConfigAssociations", reflect.TypeOf((*MockRoute53ResolverAPI)(nil).ListResolverQueryLogConfigAssociations), varargs...)
}

// ListResolverQueryLogConfigs mocks base method.
func (m *MockRoute53ResolverAPI) ListResolverQueryLogConfigs(ctx context.Context, params *route53resolver.ListResolverQueryLogConfigsInput, optFns ...func(*route53resolver.Options)) (*route53resolver.ListResolverQueryLogConfigsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListResolverQueryLogConfigs", varargs...)
	ret0, _ := ret[0].(*route53resolver.ListResolverQueryLogConfigsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListResolverQueryLogConfigs indicates an expected call of ListResolverQueryLogConfigs.
func (mr *MockRoute53ResolverAPIMockRecorder) ListResolverQueryLogConfigs(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResolverQueryLogConfigs", reflect.TypeOf((*MockRoute53ResolverAPI)(nil).ListResolverQueryLogConfigs), varargs...)
}

