// Code generated by MockGen. DO NOT EDIT.
// Source: resources/fis-api-interface.go
//
// Generated by this command:
//
//	mockgen -source resources/fis-api-interface.go -destination mocks/mock_fis/mock.go -package mock_fis
//

// Package mock_fis is a generated GoMock package.
package mock_fis

import (
	context "context"
	reflect "reflect"

	fis "github.com/aws/aws-sdk-go-v2/service/fis"
	gomock "go.uber.org/mock/gomock"
)

// MockFISAPI is a mock of FISAPI interface.
type MockFISAPI struct {
	ctrl     *gomock.Controller
	recorder *MockFISAPIMockRecorder
	isgomock struct{}
}

// MockFISAPIMockRecorder is the mock recorder for MockFISAPI.
type MockFISAPIMockRecorder struct {
	mock *MockFISAPI
}

// NewMockFISAPI creates a new mock instance.
func NewMockFISAPI(ctrl *gomock.Controller) *MockFISAPI {
	mock := &MockFISAPI{ctrl: ctrl}
	mock.recorder = &MockFISAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFISAPI) EXPECT() *MockFISAPIMockRecorder {
	return m.recorder
}

// DeleteExperimentTemplate mocks base method.
func (m *MockFISAPI) DeleteExperimentTemplate(ctx context.Context, params *fis.DeleteExperimentTemplateInput, optFns ...func(*fis.Options)) (*fis.DeleteExperimentTemplateOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteExperimentTemplate", varargs...)
	ret0, _ := ret[0].(*fis.DeleteExperimentTemplateOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExperimentTemplate indicates an expected call of DeleteExperimentTemplate.
func (mr *MockFISAPIMockRecorder) DeleteExperimentTemplate(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExperimentTemplate", reflect.TypeOf((*MockFISAPI)(nil).DeleteExperimentTemplate), varargs...)
}

// DeleteTargetAccountConfiguration mocks base method.
func (m *MockFISAPI) DeleteTargetAccountConfiguration(ctx context.Context, params *fis.DeleteTargetAccountConfigurationInput, optFns ...func(*fis.Options)) (*fis.DeleteTargetAccountConfigurationOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteTargetAccountConfiguration", varargs...)
	ret0, _ := ret[0].(*fis.DeleteTargetAccountConfigurationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTargetAccountConfiguration indicates an expected call of DeleteTargetAccountConfiguration.
func (mr *MockFISAPIMockRecorder) DeleteTargetAccountConfiguration(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTargetAccountConfiguration", reflect.TypeOf((*MockFISAPI)(nil).DeleteTargetAccountConfiguration), varargs...)
}

// ListExperimentTemplates mocks base method.
func (m *MockFISAPI) ListExperimentTemplates(ctx context.Context, params *fis.ListExperimentTemplatesInput, optFns ...func(*fis.Options)) (*fis.ListExperimentTemplatesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListExperimentTemplates", varargs...)
	ret0, _ := ret[0].(*fis.ListExperimentTemplatesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExperimentTemplates indicates an expected call of ListExperimentTemplates.
func (mr *MockFISAPIMockRecorder) ListExperimentTemplates(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExperimentTemplates", reflect.TypeOf((*MockFISAPI)(nil).ListExperimentTemplates), varargs...)
}

// ListExperiments mocks base method.
func (m *MockFISAPI) ListExperiments(ctx context.Context, params *fis.ListExperimentsInput, optFns ...func(*fis.Options)) (*fis.ListExperimentsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListExperiments", varargs...)
	ret0, _ := ret[0].(*fis.ListExperimentsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExperiments indicates an expected call of ListExperiments.
func (mr *MockFISAPIMockRecorder) ListExperiments(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExperiments", reflect.TypeOf((*MockFISAPI)(nil).ListExperiments), varargs...)
}

// ListTargetAccountConfigurations mocks base method.
func (m *MockFISAPI) ListTargetAccountConfigurations(ctx context.Context, params *fis.ListTargetAccountConfigurationsInput, optFns ...func(*fis.Options)) (*fis.ListTargetAccountConfigurationsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTargetAccountConfigurations", varargs...)
	ret0, _ := ret[0].(*fis.ListTargetAccountConfigurationsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTargetAccountConfigurations indicates an expected call of ListTargetAccountConfigurations.
func (mr *MockFISAPIMockRecorder) ListTargetAccountConfigurations(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTargetAccountConfigurations", reflect.TypeOf((*MockFISAPI)(nil).ListTargetAccountConfigurations), varargs...)
}

// StopExperiment mocks base method.
func (m *MockFISAPI) StopExperiment(ctx context.Context, params *fis.StopExperimentInput, optFns ...func(*fis.Options)) (*fis.StopExperimentOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StopExperiment", varargs...)
	ret0, _ := ret[0].(*fis.StopExperimentOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StopExperiment indicates an expected call of StopExperiment.
func (mr *MockFISAPIMockRecorder) StopExperiment(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopExperiment", reflect.TypeOf((*MockFISAPI)(nil).StopExperiment), varargs...)
}
