name: golang

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "15 3 * * 0"

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Setup tools
        run: |
          go get golang.org/x/lint/golint
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test Project
        run: |
          make test
      - name: Build Project
        run: |
          make
