name: release-drafter

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
      - docs/**

permissions:
  contents: write
  pull-requests: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          publish: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_GITHUB_TOKEN }}