name: tests

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: '1.26.x'
      - name: download go mods
        run: |
          go mod download
      - name: run go tests
        run: |
          go test -timeout 60s -race -coverprofile=coverage.txt -covermode=atomic ./...
