name: tests

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: '1.26.x'
      - name: download go mods
        run: |
          go mod download
      - name: run go tests
        run: |
          go test -timeout 60s -race -coverprofile=coverage.txt -covermode=atomic ./...
