// Code generated by MockGen. DO NOT EDIT.
// Source: resources/kinesis-streams.go
//
// Generated by this command:
//
//	mockgen -source=resources/kinesis-streams.go -destination=mocks/mock_kinesisv2/mock.go -package=mock_kinesisv2 KinesisStreamAPI
//

// Package mock_kinesisv2 is a generated GoMock package.
package mock_kinesisv2

import (
	context "context"
	reflect "reflect"

	kinesis "github.com/aws/aws-sdk-go-v2/service/kinesis"
	gomock "go.uber.org/mock/gomock"
)

// MockKinesisStreamAPI is a mock of KinesisStreamAPI interface.
type MockKinesisStreamAPI struct {
	ctrl     *gomock.Controller
	recorder *MockKinesisStreamAPIMockRecorder
	isgomock struct{}
}

// MockKinesisStreamAPIMockRecorder is the mock recorder for MockKinesisStreamAPI.
type MockKinesisStreamAPIMockRecorder struct {
	mock *MockKinesisStreamAPI
}

// NewMockKinesisStreamAPI creates a new mock instance.
func NewMockKinesisStreamAPI(ctrl *gomock.Controller) *MockKinesisStreamAPI {
	mock := &MockKinesisStreamAPI{ctrl: ctrl}
	mock.recorder = &MockKinesisStreamAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKinesisStreamAPI) EXPECT() *MockKinesisStreamAPIMockRecorder {
	return m.recorder
}

// DeleteStream mocks base method.
func (m *MockKinesisStreamAPI) DeleteStream(ctx context.Context, params *kinesis.DeleteStreamInput, optFns ...func(*kinesis.Options)) (*kinesis.DeleteStreamOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteStream", varargs...)
	ret0, _ := ret[0].(*kinesis.DeleteStreamOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteStream indicates an expected call of DeleteStream.
func (mr *MockKinesisStreamAPIMockRecorder) DeleteStream(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStream", reflect.TypeOf((*MockKinesisStreamAPI)(nil).DeleteStream), varargs...)
}

// ListStreams mocks base method.
func (m *MockKinesisStreamAPI) ListStreams(ctx context.Context, params *kinesis.ListStreamsInput, optFns ...func(*kinesis.Options)) (*kinesis.ListStreamsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListStreams", varargs...)
	ret0, _ := ret[0].(*kinesis.ListStreamsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStreams indicates an expected call of ListStreams.
func (mr *MockKinesisStreamAPIMockRecorder) ListStreams(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStreams", reflect.TypeOf((*MockKinesisStreamAPI)(nil).ListStreams), varargs...)
}

// ListTagsForStream mocks base method.
func (m *MockKinesisStreamAPI) ListTagsForStream(ctx context.Context, params *kinesis.ListTagsForStreamInput, optFns ...func(*kinesis.Options)) (*kinesis.ListTagsForStreamOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTagsForStream", varargs...)
	ret0, _ := ret[0].(*kinesis.ListTagsForStreamOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTagsForStream indicates an expected call of ListTagsForStream.
func (mr *MockKinesisStreamAPIMockRecorder) ListTagsForStream(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTagsForStream", reflect.TypeOf((*MockKinesisStreamAPI)(nil).ListTagsForStream), varargs...)
}
